services:
  mysqldb:
    image: mysql
    container_name: sqldb
    restart: always
    environment:
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=db_bead
      - MYSQL_PASSWORD=db_pass
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:3306
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysqldb
    depends_on:
      - mysqldb
  db_upload:
    build: 
      context: ./db_upload
    container_name: db_upload
    #restart: always
    depends_on:
      - mysqldb